### ISSUE TITLE
アプリのイメージ

### ISSUE THREAD

**Issue by Mizogaki** [Superbowl-tibet/SwiftBowl#2]

**Comment by Mizogaki** [comment]
![swift_logo_with_text svg](https://cloud.githubusercontent.com/assets/11548811/23575083/f6cd77b0-00ca-11e7-8d4c-1c79a68aa237.png)

**Comment by Mizogaki** [comment]
![images-1](https://cloud.githubusercontent.com/assets/11548811/23575095/0f36d0a8-00cb-11e7-8751-37e05025b46c.jpg)

**Comment by Mizogaki** [comment]
![images](https://cloud.githubusercontent.com/assets/11548811/23575096/152ffbc4-00cb-11e7-8618-55b1ebcdbd52.jpg)

**Comment by MMizogaki** [comment]
![Uploading imgres-1.jpg…]()

**Comment by Mizogaki** [comment]
![images-2](https://cloud.githubusercontent.com/assets/11548811/23575107/4b104000-00cb-11e7-9f7f-3b331e5a5fda.jpg)

**Comment by Mizogaki** [comment]
![imgres-1](https://cloud.githubusercontent.com/assets/11548811/23575108/4f91b910-00cb-11e7-8953-5d4f9bff501f.jpg)

**Comment by Mizogaki** [comment]
![imgres-2](https://cloud.githubusercontent.com/assets/11548811/23575110/537d9fda-00cb-11e7-9510-d869c4ee6e8e.jpg)
