### ISSUE TITLE
ViewとのI/F決める

### ISSUE THREAD

**Issue by watanavex** [Superbowl-tibet/SwiftBowl#3]
Viewに公開するオーディオエンジンのI/Fをprotocolを実装する

**Comment by watr** [comment]
protocol お願いします。
自分は先に、ユーザの操作を検出する方を進めておきます。

**Comment by watanavex** [comment]
`protocol AudioEngine {
    
    // 起動後テキトーに呼んでください。重複呼び出しがなければ良いです。
    func play()
    func stop()
    
    // 音を変化させるパラメータとして (0..1)
    var speed: Float { get set }
    
    // 端末のパートを表現する数値 (0..n)
    var channel: Int { get set }
    
}`
