### ISSUE TITLE
Repository名をSwiftBowlに変更してもいいですかね？？？

### ISSUE THREAD

**Issue by Mizogaki** [Superbowl-tibet/SwiftBowl#37]

**Comment by Mizogaki** [comment]
@susan335 
@watr 
@hiroaki14358 
@mitsuyoshi-yamazaki 

どうでしょうか？

**Comment by watr** [comment]
@MMizogaki よいと思います 👍

**Comment by hiroaki14358** [comment]
@MMizogaki お願いしまーす(`・ω・́)ゝ

**Comment by Mizogaki** [comment]
3896aebf01dad09169ab80fdc618fc5281e5a6a7
