### ISSUE TITLE
Class相関図を作る

### ISSUE THREAD

**Issue by Mizogaki** [Superbowl-tibet/SwiftBowl#44]

**Comment by Mizogaki** [comment]
頑張ります( ∩ˇωˇ∩)

**Comment by Mizogaki** [comment]
こいつを使います！
https://github.com/kimsungwhee/KSHObjcUML

**Comment by Mizogaki** [comment]
でけた奴
https://superbowl-tibet.github.io/SwiftBowl.github.io/ObjcUML/index.html

**Comment by hiroaki14358** [comment]
ポヨポヨ動く丸はいっぱい見えるのに、クラスに関する情報が見られない〜。なんで〜

**Comment by watanavex** [comment]
ここにチェックを入れるとクラス名が見られますね！
<img width="271" alt="img" src="https://cloud.githubusercontent.com/assets/3221619/24319286/9d75bc9a-115a-11e7-9923-5db6eee0bd8c.png">

**Comment by Mizogaki** [comment]
@susan335
正解(^^)

**Comment by hiroaki14358** [comment]
見れたよー！

しかし各ポヨポヨがもうちょっとグループ分けされてないとわかりづらいなーとも感じた。
